In [1]:
from problems.HS100 import HS100, CallableClass
import methods.methods as methods
from typing import Tuple, Union, List, Type
from copy import deepcopy
import pandas as pd
import numpy as np
from numpy import number
from scipy.stats.qmc import LatinHypercube as lhs
from scipy.stats.qmc import scale
import scipy.stats as stats
from smt.surrogate_models import KRG
import random
import itertools

In [2]:
def sample_sites(problem: dict, n_samples: int, seed=random.randint(1,1000)) -> pd.DataFrame:
    """ Simple wrapper to sample sites
    
    Parameters
    ----------
    problem : dict
        The variables and constraints given

    n_sample: int
        The number of sites to generare

    seed: int
        Seed for the LHS sampling
   
    Returns
    -------
    pd.DataFrame
        The DataFrame of sites
    """

    variables = list(problem["variables"].keys())
    nind = len(variables)
    # Get all the bounds for the variables
    bounds = np.array([problem["variables"][var]["bounds"] for var in variables])
    # Generate the experiment 
    lhs_instance = lhs(
        nind,
        scramble=True,
        strength=1,
        optimization=None,
        seed=seed,
    )
    # Get the experiment
    normalized_array = lhs_instance.random(n_samples)
    # Scale using the bounds
    exp_array = scale(normalized_array, bounds[:, 0], bounds[:, 1])
    # Create the DataFrame
    exp_df = pd.DataFrame(data=exp_array, columns=variables)
    return(exp_df)

In [3]:
def evaluate_sites(local_eval: CallableClass, exp_data: pd.DataFrame, verbose=True):
    """ evaluates sites passed and returns their constraint violation data

        Parameters
        ----------
        local_eval : CallableClass
            The example evaluator to use
        
        n_sample: int
            The number of sites to generare
   
        Returns
        -------
        pd.DataFrame
            The DataFrame of evaluated experimental sites with constraint violation
    """
    eps = 1e-6
    local_problem = local_eval.problem()
    local_eval(exp_data)
    my_constraint_calculator = methods.ConstraintCalculator(local_problem)
    exp_data['__conviol__'] = my_constraint_calculator(exp_data)
    exp_data['__State__'] = pd.cut(exp_data['__conviol__'], [-np.inf, eps, 100*eps, np.inf], include_lowest=True, labels=['Feasible', 'Nearly Feasible', "Infeasible"]).astype("str")
    feasible_sites = (exp_data['__State__'] == 'Feasible').sum()
    percentage = feasible_sites/len(exp_data) * 100
    if verbose: 
        print(f"Test evaluator {local_eval.name} with {len(local_problem['variables'])} variables {percentage}% feasible sites")
    return (exp_data)

In [4]:
def advanced_testing(local_eval: CallableClass, num_sites_training: int, num_sites_testing : int, verbose=True) -> pd.DataFrame:
    """ Wrapper to create an experiment, evaluate the passed in function, create a surrogate model, evaluate model

        Parameters
        ----------
        local_eval : CallableClass
            The example evaluator to use
        
        n_sample_training: int
            The number of sites to train the sm on

        n_sample_testing: int
            The number of sites to test the sm
   
        Returns
        -------
        pd.DataFrame
            The DataFrame of evaluated experimental sites with constraint violation
    """
    # get training data
    sample_data = sample_sites(local_eval.problem(), num_sites_training)
    exp_data = evaluate_sites(local_eval, sample_data, verbose=False)
    variables = list(local_eval.problem()["variables"].keys())
    xt = exp_data[variables].to_numpy()
    yt = exp_data['__conviol__'].to_numpy()

    # create model
    sm = KRG(theta0=[1e-2])
    sm.set_training_values(xt, yt)
    sm.train()

    # get testing data
    eps = 1e-6
    x = sample_sites(local_eval.problem(), num_sites_testing).to_numpy()
    y = sm.predict_values(x).flatten()
    feasible_points = pd.DataFrame(data=x[y < eps], columns=variables)
    
    # evaluate model on testing data
    feasible_points = evaluate_sites(local_eval, feasible_points, verbose=verbose)
    return (feasible_points)

In [7]:
hs100 = HS100()
problem = hs100.problem()
nind = len(problem['variables'])
num_sites = 50
test_data = advanced_testing(hs100, num_sites, num_sites**2)
test_data

___________________________________________________________________________

                                  Kriging
___________________________________________________________________________

 Problem size

      # training points.        : 50

___________________________________________________________________________

 Training

   Training ...
   Training - done. Time (sec):  1.5636711
___________________________________________________________________________

 Evaluation

      # eval points. : 2500

   Predicting ...
   Predicting - done. Time (sec):  0.0545983

   Prediction time/pt. (sec) :  0.0000218

Test evaluator hs100 with 7 variables 3.6585365853658534% feasible sites

,x1,x2,x3,x4,x5,x6,x7,f,c1,c2,c3,c4,__conviol__,__State__
0,-7.356006,1.684909,0.103228,9.380982,-9.479817,-9.576386,0.009349,7.259291e+06,-310.115442,309.469956,-187.819052,-208.501349,2.823305,Infeasible
1,-7.912730,0.602388,2.298096,-3.036976,0.740286,2.601353,1.174653,1.592681e+03,-41.510046,286.546739,346.424932,-275.755750,2.757870,Infeasible
2,-8.579630,-0.516721,-2.033648,5.278082,4.477786,-4.491598,6.611062,8.401445e+04,-152.221820,301.450036,324.906254,-194.499137,1.950939,Infeasible
3,5.753873,1.214276,-2.314833,-3.482967,3.697230,-5.206371,4.683332,2.758284e+04,-10.431826,191.675729,-62.984707,-46.110739,0.780664,Infeasible
4,-2.570543,0.183960,2.673245,8.847172,0.353117,-2.317571,-4.552320,1.405564e+03,-203.747487,219.485472,186.443280,-80.663386,0.831968,Infeasible
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,-6.109804,0.243273,-4.297239,0.580643,3.278721,0.627939,7.836116,1.772498e+04,38.885124,142.074275,396.789404,-107.712000,1.077120,Infeasible
78,-1.345976,0.583526,5.698205,0.282913,-5.723174,-9.652852,0.071897,3.543464e+05,145.626379,-41.030219,-331.873176,-25.827293,3.353958,Infeasible
79,-7.247852,-0.891753,2.250072,-0.626014,-1.618562,-5.186040,2.116647,2.026566e+03,24.315307,283.789451,217.468506,-152.443101,1.524431,Infeasible
80,4.503210,1.544873,-0.890597,8.527119,-1.682465,-2.734015,3.183150,1.014231e+03,-212.189957,227.701704,70.655723,-15.533153,0.262969,Infeasible
81,-0.538846,0.730958,-1.216639,3.148774,-7.224656,-2.662491,7.749868,1.426649e+06,123.243656,258.403509,227.324967,92.723237,0.000000,Feasible

## Experiment 3
1. Generate training data once and train
2. Regenerate sites, pass through filter, take the top sites
3. Train again, and repeat

In [8]:
# multi-run training
def experiment_3(local_eval, sites_per_run, runs, verbose=False):
    problem = hs100.problem()
    nind = len(problem['variables'])

    # create model
    sm = KRG(theta0=[1e-2], print_global=False)
    
    for i in range(runs):
        if i == 0:
            # get first run's data
            sample_data = sample_sites(local_eval.problem(), sites_per_run)
            exp_data = evaluate_sites(local_eval, sample_data, verbose=False)
            training_data = exp_data
        else:
            training_data = pd.concat([training_data, exp_data], axis=0)
        variables = list(local_eval.problem()["variables"].keys())
        xt = training_data[variables].to_numpy()
        yt = training_data['__conviol__'].to_numpy()
        
        # train model
        sm.set_training_values(xt, yt)
        sm.train()
    
        # get next run's data
        x = sample_sites(local_eval.problem(), sites_per_run**2).to_numpy()
        y = sm.predict_values(x)
        exp_data = pd.DataFrame(data=np.concatenate((x,y), axis=1), columns=variables + ['conviol'])
        exp_data = exp_data.sort_values(by='conviol').reset_index()[:sites_per_run].drop('conviol',axis=1)
        # evaluate model on testing data
        exp_data = evaluate_sites(local_eval, exp_data)
    return exp_data

In [9]:
hs100 = HS100()
problem = hs100.problem()
nind = len(problem['variables'])
num_sites = 20
runs = 3
experiment_3(hs100, num_sites, runs)

Test evaluator hs100 with 7 variables 0.0% feasible sites
Test evaluator hs100 with 7 variables 5.0% feasible sites

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/smt/surrogate_models/krg_based.py:533: UserWarning: Warning: multiple x input features have the same value (at least same row twice).
  warnings.warn(

Test evaluator hs100 with 7 variables 15.0% feasible sites

,index,x1,x2,x3,x4,x5,x6,x7,f,c1,c2,c3,c4,__conviol__,__State__
0,301,-4.664128,-1.171352,1.597575,0.907745,9.753119,2.903422,8.758165,8.614321e+06,24.184968,301.485875,321.389032,4.719815,0.000000,Feasible
1,132,-3.578861,-1.332019,-2.574172,1.011708,5.313399,-4.168953,3.654994,2.268169e+05,63.852313,249.086157,201.498496,9.091030,0.000000,Feasible
2,114,-1.862814,-1.423673,5.416841,-7.152191,10.002242,-1.603361,6.223002,1.001787e+07,-152.307851,23.043445,271.177289,9.834456,0.152308,Infeasible
3,326,1.282972,-2.172216,-2.671736,-0.313651,-6.184597,4.730255,2.786010,5.611980e+05,90.115771,202.283152,49.809316,-26.944792,0.269448,Infeasible
4,399,-4.204936,-3.195676,-0.995410,-7.400557,-3.563290,6.593896,5.172775,2.361910e+04,-421.499994,314.950440,63.006612,-18.676089,0.461023,Infeasible
5,101,-1.093317,-1.136690,-1.664435,-3.899571,7.471175,-0.803136,-8.371757,1.745760e+06,23.082977,276.730611,149.010019,-95.959483,0.959595,Infeasible
6,31,-0.289686,1.327196,-5.175165,2.441672,-3.252027,0.727628,3.808785,1.360615e+04,115.112314,6.529231,228.194952,-18.556694,0.185567,Infeasible
7,340,-2.073774,-1.883460,5.968596,-1.021490,-3.983078,4.000195,6.178122,4.412400e+04,90.419317,-57.036113,193.565013,-32.321861,0.655578,Infeasible
8,76,-1.527878,-3.860026,0.573181,9.480112,-7.541841,3.148470,-2.747663,1.841746e+06,-866.034886,283.967908,134.782915,-53.168209,1.016220,Infeasible
9,385,-6.448483,-1.413204,-0.417929,5.231665,8.839675,7.481161,5.304625,4.773270e+06,-121.393388,333.240355,48.948359,-120.394072,1.210045,Infeasible
10,53,-4.747683,-0.488149,-1.151073,0.107932,-7.782057,-0.256405,-7.323382,2.225377e+06,121.763436,295.558541,245.976889,-165.372634,1.653726,Infeasible
11,374,3.928174,-0.720168,-1.059914,2.933421,-0.024876,-4.846217,9.394805,9.152419e+03,62.096382,242.470812,39.376890,54.599438,0.000000,Feasible
12,371,-2.687210,3.475261,1.297068,1.540975,9.273024,1.163254,0.489160,6.358902e+06,-382.196318,281.292879,241.522704,-72.778359,0.822036,Infeasible
13,368,-9.130419,-0.880152,-2.945629,-8.615876,-6.361838,1.347958,6.098354,6.666983e+05,-303.707856,264.040107,443.109857,-267.135735,2.688566,Infeasible
14,191,-0.121585,2.419287,0.772099,7.916016,-6.716902,-4.525016,9.178970,9.263327e+05,-193.641472,254.998941,143.520658,115.606948,0.193641,Infeasible
15,238,-2.624967,0.858255,-2.141657,-6.349444,-8.211912,-4.192809,-5.484730,3.069387e+06,-6.469172,250.070573,106.281915,-83.598457,0.836010,Infeasible
16,30,1.953565,-0.857374,-0.551188,7.095548,-8.126473,6.875719,5.318180,2.881945e+06,-42.457576,252.637062,-90.774677,2.488209,0.908739,Infeasible
17,313,-4.519112,-0.432131,-3.006427,0.199642,2.335479,-6.128921,0.391685,3.368728e+03,77.220234,226.679995,77.504325,-59.141767,0.591418,Infeasible
18,194,-3.934868,-0.320636,-4.447196,-8.216452,5.412145,5.749806,0.613315,2.539211e+05,-196.651949,126.359084,92.944047,-119.808235,1.214114,Infeasible
19,108,-0.830124,-4.398841,4.083348,-7.479335,-2.164825,-4.961839,8.264093,8.777764e+03,-1214.643290,139.584591,114.136718,71.215278,1.214643,Infeasible

## Experiment 4
1. Train to minimize $\log(C+\epsilon)$
3. Filter is now if EI(x) is sufficiently large,
    $EI(x) = (f^*-\mu_f(x))\Phi\left(\frac{f^*-\mu_f(x)}{\sigma_f(x)}\right)+\sigma_f(x)\phi\left(\frac{f^*-\mu_f(x)}{\sigma_f(x)}\right)$
   where $\mu_f,\sigma_f, f^*$ are the predicted value, variance, and maximum of the sm, and $\Phi,\phi$ are normal CDF and PDF.
   
   Note: Need to choose test sites wisely and tune filter better

In [22]:
# weigh with variance
def experiment_4(local_eval, num_sites_training, num_sites_testing,verbose=True):
    # get training data
    sample_data = sample_sites(local_eval.problem(), num_sites_training)
    exp_data = evaluate_sites(local_eval, sample_data, verbose=False)
    variables = list(local_eval.problem()["variables"].keys())
    xt = exp_data[variables].to_numpy()
    yt = (-1) * (1 / (exp_data['__conviol__'].to_numpy()+1e-6))
    
    # create model
    sm = KRG(theta0=[1e-2], print_global=False)
    sm.set_training_values(xt, yt)
    sm.train()

    # compute EI(x)
    x = sample_sites(local_eval.problem(), num_sites_testing**2).to_numpy()
    mu = sm.predict_values(x)
    sigma = np.sqrt(sm.predict_variances(x))
    y_min = np.min(mu)
    t = (y_min-mu)/sigma
    EI_x = (y_min-mu)*stats.norm.cdf(t) + sigma*stats.norm.pdf(t)
    feasible_points = pd.DataFrame(data=np.concatenate((x, EI_x), axis=1), columns=variables + ['EI'])
    
    feasible_points = feasible_points.sort_values(by='EI', ascending=False).reset_index()[:num_sites_testing] #.drop('EI',axis=1)
    
    # evaluate model on testing data
    feasible_points = evaluate_sites(local_eval, feasible_points, verbose=verbose)
    return (feasible_points)

In [24]:
hs100 = HS100()
problem = hs100.problem()
nind = len(problem['variables'])
training_sites = 50
testing_sites = 50
experiment_4(hs100, training_sites, testing_sites)

Test evaluator hs100 with 7 variables 0.0% feasible sites

,index,x1,x2,x3,x4,x5,x6,x7,EI,f,c1,c2,c3,c4,__conviol__,__State__
0,679,-8.260094,0.788128,0.778986,-9.789547,-5.672893,3.838653,1.050113,0.087613,3.355946e+05,-366.371198,335.504742,305.350378,-301.923471,3.041382,Infeasible
1,1676,-3.579978,0.411640,1.281654,-8.145559,-4.947693,-6.096026,2.051843,0.044696,1.490260e+05,-140.662309,292.596418,71.615601,-6.090268,0.153281,Infeasible
2,2455,-7.521904,-0.530051,1.753901,-5.436081,1.051545,7.775676,1.775518,0.044617,2.211427e+03,-111.610452,311.969410,20.160212,-240.136182,2.403954,Infeasible
3,216,3.108280,0.890385,-1.152500,-7.011377,3.820184,-7.578790,1.072797,0.027788,3.322450e+04,-108.794389,255.119886,-212.329180,15.902505,2.126077,Infeasible
4,2257,0.863320,0.064559,0.967450,1.894192,8.102075,5.057671,-0.138517,0.023467,2.829817e+06,69.679632,272.611377,21.551145,-31.502210,0.315022,Infeasible
5,2073,-3.683872,0.770551,0.268273,-6.837165,9.031836,9.536416,2.749114,0.018719,5.430448e+06,-133.614173,320.624748,-243.531180,-80.978991,2.569894,Infeasible
6,774,-9.354785,-0.457726,1.074215,0.140571,9.550787,2.082607,3.002849,0.009846,7.591430e+06,-97.062900,346.727521,408.949827,-317.101331,3.172498,Infeasible
7,2464,4.114552,-1.137857,-0.713945,-8.530247,-4.386549,-3.654540,1.626568,0.009343,7.343230e+04,-180.301712,255.658227,32.949167,-47.912686,0.511929,Infeasible
8,940,-1.684469,1.092176,-1.395023,2.194810,-7.252828,-9.338910,0.053833,0.009006,1.457281e+06,135.446857,261.606216,-289.310814,25.332727,2.893108,Infeasible
9,1917,-2.555098,-0.522428,2.793384,-8.716063,9.912365,0.543394,2.280357,0.007695,9.487748e+06,-242.514783,242.051457,270.965514,-15.621495,0.288473,Infeasible
10,760,-1.291879,-0.100470,0.442610,-8.894485,-6.143840,-1.357923,3.397000,0.006022,5.400209e+05,-162.509050,292.136171,241.815402,37.468298,0.162509,Infeasible
11,478,-5.903369,-0.123871,-1.080767,5.417210,3.982723,8.484312,2.445282,0.004683,4.134488e+04,-78.917734,310.580134,-80.576941,-155.080211,1.749423,Infeasible
12,1457,2.319559,-0.618784,1.853302,8.782459,-9.668848,4.066302,1.974725,0.004535,8.171421e+06,-146.235961,214.820847,58.856169,-31.689230,0.349007,Infeasible
13,958,-0.417021,2.166370,0.115350,-5.793118,-9.901693,5.863937,2.324375,0.004118,9.426043e+06,-24.272797,274.178406,13.178774,-11.877225,0.121227,Infeasible
14,536,-9.916990,0.100610,1.269123,1.759250,3.647285,9.317450,3.469326,0.003573,2.540642e+04,-101.579082,336.898409,-69.054027,-408.036146,4.139627,Infeasible
15,1170,0.584428,-1.836036,0.353256,-7.294324,-1.564020,8.736258,2.408776,0.003139,2.573379e+03,-113.136397,287.899514,-259.475864,-25.390680,2.609606,Infeasible
16,876,9.919008,0.123307,-2.308228,-6.070831,1.117841,-2.855049,1.291754,0.003036,1.720235e+03,-220.475055,166.106526,-70.726209,-372.064152,3.793679,Infeasible
17,519,-6.454624,-0.332963,0.085185,0.878192,-3.616492,4.136406,3.441875,0.002877,2.384593e+04,58.551165,323.614012,269.221345,-143.148030,1.431480,Infeasible
18,331,-4.791370,1.063778,-0.123729,4.705634,-0.519987,-2.589000,-1.046319,0.002630,1.007388e+03,-8.604464,306.969545,256.481816,-106.846522,1.068500,Infeasible
19,302,0.575736,2.356980,-1.252599,2.869066,2.440115,-1.459318,-0.461635,0.001702,2.895970e+03,-10.122926,254.779916,160.731991,-3.729650,0.038646,Infeasible
20,192,-6.136643,2.287659,1.330506,-8.043085,-1.851278,-4.756656,2.225582,0.001238,2.480671e+03,-281.320647,306.582882,213.959386,-153.258374,1.558189,Infeasible
21,1039,-4.846376,1.893329,0.002879,9.331152,6.723865,-7.708081,-0.747626,0.001234,9.253053e+05,-340.428608,307.637276,-58.586139,-94.744986,1.164812,Infeasible
22,2266,1.700057,1.579925,2.299094,6.020296,-2.318265,2.699113,0.254739,0.000837,2.285642e+03,-33.156498,204.162933,112.729177,-27.264153,0.274650,Infeasible
23,2008,3.485096,0.138034,1.474701,-3.729844,-2.951045,4.582393,4.131869,0.000831,8.290179e+03,60.340716,236.221607,22.888752,-28.970324,0.289703,Infeasible
24,240,4.971788,-0.697301,-0.792591,8.584225,-6.683706,-7.282905,-0.086180,0.000748,8.927557e+05,-183.691143,227.739452,-237.771008,-75.551287,2.501609,Infeasible
25,911,3.988355,-0.784186,2.187293,8.365376,-0.713811,1.698037,3.266974,0.000648,9.671453e+02,-184.484758,199.512378,112.488694,-55.747656,0.587209,Infeasible
26,1274,-1.891108,2.265491,-0.825512,1.475870,7.922304,-0.882226,2.698599,0.000549,2.473287e+06,-6.677425,288.073011,251.281895,0.442313,0.006677,Infeasible
27,359,4.260256,0.856258,-1.573764,9.428294,-2.022838,-1.605399,2.784242,0.000504,1.442318e+03,-254.795136,213.390956,104.091031,-28.688473,0.383697,Infeasible
28,570,-8.364735,1.751838,-2.238448,-2.258535,7.212232,5.464151,2.317011,0.000427,1.408931e+06,-95.419345,294.661917,224.714367,-338.759995,3.388944,Infeasible
29,1391,-9.014802,2.465391,-2.336945,-1.756718,8.171048,-6.691629,1.422664,0.000421,2.977976e+06,-197.227634,293.022083,139.976213,-359.634976,3.601754,Infeasible
30,426,-3.553861,1.308479,-1.511561,0.303962,6.944132,9.615970,3.109337,0.000410,1.122868e+06,59.367435,286.743584,-253.899936,-84.629075,2.676327,Infeasible
31,356,8.326818,-0.226712,-2.304755,-2.638870,1.593554,-8.773432,-0.437470,0.000404,2.115022e+03,-45.197276,175.505869,-460.906593,-254.627186,5.265836,Infeasible
32,1753,4.914328,-2.216744,2.553987,-9.401122,7.715056,-8.659355,2.930810,0.000388,2.111887e+06,-388.395802,206.137628,-348.403638,-71.707873,3.578207,Infeasible
33,1539,2.177474,-1.187859,2.590671,9.077826,5.186636,0.062528,1.962616,0.000386,1.956620e+05,-246.607176,199.314310,160.184554,-20.283195,0.319305,Infeasible
34,2015,8.084513,2.306524,-0.607862,-5.886284,2.505442,5.986955,3.232162,0.000234,3.999444e+03,-239.140257,223.185603,-184.468309,-205.936067,2.775069,Infeasible
35,245,5.260379,0.837032,1.613333,2.957613,1.619003,-6.875301,-1.348976,0.000201,1.403073e+03,25.485958,215.299218,-220.099748,-83.845580,2.355292,Infeasible
36,769,2.143483,3.647626,-0.920443,-4.782638,-6.086573,-4.836100,0.754962,0.000181,5.098166e+05,-473.413357,246.276659,-0.892771,22.563276,0.473498,Infeasible
37,1033,7.306615,3.143251,0.595813,-5.643827,6.655632,-1.542466,-0.875886,0.000163,8.704969e+05,-433.903029,230.173467,-3.214457,-157.159341,1.630709,Infeasible
38,2243,6.604172,3.495275,0.092408,0.039266,-0.681588,-2.602511,0.307912,0.000158,8.087868e+02,-404.682106,224.478722,-6.288006,-101.044618,1.090286,Infeasible
39,1141,-5.080387,-2.768140,2.657557,-9.009283,2.756752,7.768543,2.691659,0.000136,7.250191e+03,-441.876948,267.007062,-35.381977,-92.073931,1.080835,Infeasible
40,1443,8.559764,0.584853,1.236541,9.153660,-0.214162,-6.927242,-1.338337,0.000098,1.048178e+03,-355.213865,195.668936,-299.843432,-261.545264,3.994669,Infeasible
41,284,6.035708,0.927280,3.544550,-9.436358,-4.034865,-5.898283,-0.720936,0.000096,4.548038e+04,-287.627209,116.731322,-158.187084,-133.355092,2.088876,Infeasible
42,1150,-9.273221,2.835559,0.767440,9.601932,4.431335,-6.606626,1.529373,0.000088,7.692227e+04,-630.641524,327.345635,151.593666,-382.216901,3.873846,Infeasible
43,2389,-3.267551,-0.672203,-1.119744,2.614812,7.936052,7.036954,-1.243590,0.000083,2.499713e+06,39.124221,299.672443,-36.359218,-87.941966,0.951619,Infeasible
44,1246,4.994652,1.521185,-2.798310,4.724685,2.732994,-7.022476,1.910593,0.000080,5.387764e+03,-39.114199,162.176818,-201.797270,-38.839005,2.055381,Infeasible
45,2170,-6.796060,-0.724583,-2.622472,4.176839,-6.327632,-4.187435,0.749133,0.000063,6.433203e+05,-1.723097,252.468091,252.569747,-155.074869,1.550750,Infeasible
46,2302,1.127287,-2.190445,-0.365579,-1.126087,-7.095278,-6.214329,1.205976,0.000058,1.277781e+06,86.164305,273.374650,-56.785163,26.781150,0.567852,Infeasible
47,623,-2.295656,-1.098667,-2.052174,-4.926324,-9.143770,5.512355,-1.079251,0.000054,5.846540e+06,62.785258,255.033957,56.642687,-62.577110,0.625771,Infeasible
48,1000,2.619727,2.883751,-1.429107,-1.915993,-8.402647,2.824231,-1.679508,0.000053,3.520669e+06,-65.436220,228.100524,66.136517,-49.784410,0.502126,Infeasible
49,1720,1.352088,3.442183,-2.327317,3.822889,-2.983498,-7.271716,1.080509,0.000043,8.144537e+03,-339.039188,201.238378,-155.569720,32.212574,1.592213,Infeasible

# Experiment 5
We select sites sparsely
1. Sort the sites by their score through the model
2. Select the next possible site and delete the others that are too close
3. Continue until we are left with the appropriate number of sites

In [15]:
# filter points that are too close
def experiment_5(local_eval, num_sites_training, num_sites_testing,verbose=True):
    # get training data
    sample_data = sample_sites(local_eval.problem(), num_sites_training)
    exp_data = evaluate_sites(local_eval, sample_data, verbose=False)
    variables = list(local_eval.problem()["variables"].keys())
    xt = exp_data[variables].to_numpy()
    yt = (-1)*np.log(exp_data['__conviol__'].to_numpy() + 1e-6)
    
    # create model
    sm = KRG(theta0=[1e-2], print_global=False)
    sm.set_training_values(xt, yt)
    sm.train()

    # filter points
    x = sample_sites(local_eval.problem(), num_sites_testing**2).to_numpy()
    y = sm.predict_values(x)
    exp_data = pd.DataFrame(data=np.concatenate((x,y), axis=1), columns=variables + ['conviol'])
    exp_data = exp_data.sort_values(by='conviol').reset_index().drop('conviol',axis=1).drop('index', axis=1).to_numpy()
    eps = 3 # not sure how to decide this
    feasible_points = np.zeros((1,len(variables)))
    
    total_filtered = 0
    
    while len(feasible_points) < num_sites_testing and len(exp_data) > 0:
        feasible_points = np.append(feasible_points, np.array([exp_data[0]]), axis=0)
        exp_data = exp_data[1:]
        dists = np.linalg.norm(exp_data - feasible_points[-1], axis=1)
        total_filtered += len(exp_data) - len(exp_data[dists > eps])
        exp_data = exp_data[dists > eps]

    print(total_filtered)
    feasible_points = feasible_points[1:]
    # evaluate model on testing data
    feasible_points = pd.DataFrame(data=feasible_points, columns=variables)
    feasible_points = evaluate_sites(local_eval, feasible_points)
    return feasible_points

In [16]:
hs100 = HS100()
problem = hs100.problem()
nind = len(problem['variables'])
training_sites = 50
testing_sites = 50
experiment_5(hs100, training_sites, testing_sites)

10
Test evaluator hs100 with 7 variables 0.0% feasible sites

,x1,x2,x3,x4,x5,x6,x7,f,c1,c2,c3,c4,__conviol__,__State__
0,5.468062,-9.556861,-7.167657,-3.979241,1.951264,-4.674979,-2.113280,6.405600e+03,-25024.203151,-235.428372,-169.137813,-470.326691,25.626839,Infeasible
1,5.396185,-9.417534,-7.164637,6.382315,8.048091,-4.850855,-9.939634,2.732296e+06,-23724.965774,-239.175147,-237.504022,-545.367194,24.575960,Infeasible
2,5.477992,-9.688072,-5.253661,-7.766867,6.212610,3.260809,6.216735,5.805645e+05,-26628.507780,10.688212,-37.915913,-376.227716,26.895649,Infeasible
3,-1.557925,5.538441,-8.993161,8.013662,9.149627,-4.836911,-5.462820,5.875009e+06,-2994.227272,-531.343383,17.081165,-263.928641,6.645586,Infeasible
4,-3.756145,5.639837,-7.360415,-6.195151,-3.562549,1.355092,6.113247,2.597141e+04,-3064.764920,-247.750982,288.471922,-199.675577,4.417904,Infeasible
5,5.355549,-9.353578,-6.951836,-5.429836,-0.327167,2.737805,1.063016,5.453099e+03,-23002.908166,-205.605687,-51.136392,-451.149594,23.536700,Infeasible
6,6.584168,-9.932584,-9.831532,-3.309017,-2.802215,-8.491850,-1.854662,1.776926e+04,-29178.809025,-700.374769,-501.598504,-639.514755,31.088799,Infeasible
7,-1.513403,5.550631,-7.950076,-5.855569,-4.460798,-9.664308,1.421122,8.477639e+04,-2832.154344,-354.700370,-349.025369,-127.625607,5.866262,Infeasible
8,-3.428178,9.890177,2.660410,0.860212,-9.523953,5.974382,-0.024832,7.463579e+06,-28558.179988,195.164752,-37.325582,-290.841720,28.708324,Infeasible
9,-5.017156,5.117530,-8.536933,2.177663,8.234913,-8.859929,4.670255,3.125809e+06,-2032.559317,-420.967473,-148.422521,-253.988881,5.523280,Infeasible
10,2.049062,-9.896232,-5.102655,-7.899589,1.508922,0.392554,9.076480,1.102515e+04,-28907.488541,46.382881,122.623407,-129.759684,28.936597,Infeasible
11,1.377351,-9.939053,-8.749698,7.147014,-1.661871,-7.125535,-9.043765,1.552797e+04,-29339.345493,-472.205265,-311.453421,-364.409980,30.101076,Infeasible
12,4.258607,-9.561181,-4.723350,9.359693,-2.153798,-6.302113,-4.130832,4.422550e+03,-25314.954550,46.259442,-264.710534,-344.659709,25.685271,Infeasible
13,-6.206435,10.062505,5.540953,-9.541624,8.838345,-2.865617,-2.730707,4.769407e+06,-31121.059745,6.615888,166.377782,-519.804214,31.552179,Infeasible
14,-1.441432,5.399808,-7.476007,8.917141,0.028660,5.024512,-1.101342,3.644394e+03,-2738.439227,-291.904730,39.709938,-209.837908,4.519190,Infeasible
15,1.734018,-9.727975,-5.503492,-9.900288,-4.155969,9.532852,-3.233666,5.698287e+04,-27111.292376,1.905884,-509.636831,-301.077664,27.749954,Infeasible
16,-4.464386,5.019494,-6.906432,-1.757607,9.203515,-1.409326,-5.498256,6.081636e+06,-1868.741381,-167.834664,217.582318,-320.976966,4.075741,Infeasible
17,8.388024,-9.882603,-8.622395,-4.591888,-5.220962,-8.662681,-0.199149,2.117964e+05,-28679.185746,-491.154362,-546.435827,-735.356811,30.504969,Infeasible
18,-7.553660,9.966840,1.002070,0.970335,-3.135206,-1.031890,3.615808,1.030352e+04,-29580.267924,290.828111,292.933948,-510.502351,30.017553,Infeasible
19,5.648275,-9.087153,-8.953610,-9.079260,8.312967,7.172599,-7.860822,3.314444e+06,-20755.706905,-514.555636,-388.050336,-646.834929,22.675404,Infeasible
20,3.413464,-9.206749,-9.777118,0.089984,-8.701016,-2.540088,8.479728,4.356347e+06,-21397.980460,-678.985287,61.851640,-310.858509,22.663605,Infeasible
21,6.619053,-9.251712,-9.939950,-4.355573,-9.361566,8.586223,-1.343007,6.744407e+06,-21958.848434,-729.610277,-494.915790,-699.863706,24.675883,Infeasible
22,-4.074531,5.835163,-9.587315,9.574099,5.206128,-2.530127,-6.665208,2.099806e+05,-3767.329962,-630.517768,163.934164,-416.282843,8.442581,Infeasible
23,-0.685022,9.825378,6.077215,-3.085480,-2.164595,-0.617300,3.233623,3.225951e+03,-27866.065005,-111.085553,138.800083,-153.815626,27.930584,Infeasible
24,1.089957,-9.342738,-6.984912,-9.294204,5.318502,-9.271895,10.054510,2.435065e+05,-23097.447871,-170.878692,-351.727872,-63.207235,23.434650,Infeasible
25,-4.053258,9.532435,2.531448,-9.019614,-9.281256,-8.952438,-5.794758,6.395142e+06,-24957.999676,217.431562,-328.877338,-304.291792,25.356994,Infeasible
26,1.755971,-9.922064,-3.262818,5.313402,-5.945590,0.356316,6.998601,4.467549e+05,-29034.754832,181.755568,112.392348,-109.138604,29.055260,Infeasible
27,-3.478075,3.764165,-9.414594,-7.009724,0.232684,-4.976033,7.002837,1.206129e+04,-687.764199,-584.049317,169.284057,-177.190869,6.141990,Infeasible
28,-2.114496,10.074458,1.436791,-2.898133,-0.927660,-9.893000,7.355190,4.698339e+03,-30815.866048,247.904902,-385.248516,-57.042943,31.060982,Infeasible
29,8.489800,-9.579607,-9.975396,7.762393,9.134481,-0.178417,-1.129611,5.821300e+06,-25558.449008,-742.402903,-100.262167,-834.613246,27.910817,Infeasible
30,-0.177761,-9.675704,-7.789916,5.266131,-5.877873,4.709161,-0.665794,4.187623e+05,-26240.500070,-305.700429,-31.914304,-240.820880,26.529426,Infeasible
31,-6.537514,9.563732,1.569108,-0.733787,2.606233,1.543054,-6.419662,5.646783e+03,-25072.754130,277.790423,189.254447,-533.246157,25.633536,Infeasible
32,5.716840,-9.305422,-3.705886,-7.929934,-8.206252,-9.822203,-2.290428,3.058282e+06,-22639.105671,132.286141,-619.255667,-380.463648,23.777134,Infeasible
33,3.677845,-9.715043,-2.022907,-2.997360,-3.154283,3.634188,-6.759878,1.514805e+04,-26642.119829,244.321775,-116.295439,-356.393393,26.904584,Infeasible
34,-8.484376,9.624259,1.632943,9.827390,9.564141,6.938579,7.985598,7.658209e+06,-26191.663208,285.589563,73.535805,-577.716748,26.821239,Infeasible
35,8.463418,-9.214705,-6.799346,-9.905329,-0.063183,-4.789215,1.715446,5.937341e+03,-22031.136254,-202.068783,-207.465342,-655.038505,23.166050,Infeasible
36,-8.624702,9.635080,1.245086,3.952010,9.368298,-9.172968,6.493137,6.763443e+06,-25987.211456,303.381576,-151.381532,-525.486870,26.556363,Infeasible
37,8.198225,-9.763534,-2.732133,-6.452314,-1.081390,-9.315844,0.189602,4.063167e+03,-27427.290669,184.628471,-607.078704,-570.565350,28.664703,Infeasible
38,-7.541943,10.055079,5.865667,-5.033056,0.371220,8.521505,8.192515,6.864651e+03,-30762.238395,-34.027799,-101.796069,-577.434632,31.317893,Infeasible
39,-2.520951,10.047162,0.852503,2.937636,8.219098,-2.248483,-3.679978,3.083405e+06,-30532.132397,267.519030,93.262542,-233.042312,30.620940,Infeasible
40,-6.212364,9.368177,4.034500,3.673523,6.373010,-3.066238,-4.465764,6.711876e+05,-23146.957693,137.309587,158.984629,-483.078757,23.645679,Infeasible
41,-1.850926,9.707915,7.008463,-8.223531,-1.039034,-0.632169,-2.225774,3.746401e+03,-26797.746739,-218.168373,124.123658,-281.412985,27.033281,Infeasible
42,-7.087418,9.893709,-0.482386,-5.917991,1.776610,3.957619,7.834146,5.137442e+03,-28866.657258,307.298434,229.821803,-443.251863,29.204985,Infeasible
43,9.401266,-9.458456,-6.836138,-1.290970,-3.243550,-4.237959,9.564941,2.520820e+04,-24043.933845,-224.713968,-140.933773,-676.823381,25.118830,Infeasible
44,9.629011,-9.948196,-4.571157,9.005735,6.769771,2.047863,0.908420,9.654479e+05,-29795.290811,33.250816,-142.328963,-799.249563,30.881468,Infeasible
45,9.907549,-0.920241,-9.350483,7.076700,9.084061,-8.092149,4.464054,5.628844e+06,-307.859041,-656.899996,-389.905296,-506.134648,9.168772,Infeasible
46,-9.576012,9.927022,-0.445428,-3.326469,7.876232,-0.489634,9.683252,2.397082e+06,-29273.404199,328.469654,393.730076,-641.962535,29.969047,Infeasible
47,-4.563152,6.263113,-9.098782,1.720692,1.742990,-8.023114,-7.508691,1.129785e+04,-4542.279065,-532.703234,-184.565777,-416.310327,8.351494,Infeasible
48,-0.250031,4.826850,-8.095222,-3.968260,-6.374706,-3.621981,-6.173414,6.779289e+05,-1524.602801,-388.462960,50.352445,-208.032021,4.662885,Infeasible

# Experiment 6
TODO: Combining the other parts together

In [22]:
# multi-run training
def experiment_6(local_eval, sites_per_run, runs, verbose=False):
    problem = hs100.problem()
    eps = 1e-6
    nind = len(problem['variables'])

    # create model
    sm = KRG(theta0=[1e-2], print_global=False)
    
    for i in range(runs):
        if i == 0:
            # get first run's data
            sample_data = sample_sites(local_eval.problem(), sites_per_run)
            exp_data = evaluate_sites(local_eval, sample_data, verbose=False)
            training_data = exp_data
        else:
            training_data = pd.concat([training_data, exp_data], axis=0)
        variables = list(local_eval.problem()["variables"].keys())
        xt = training_data[variables].to_numpy()
        yt = np.log(training_data['__conviol__'].to_numpy() + eps)
        
        # train model
        sm.set_training_values(xt, yt)
        sm.train()

        # compute EI
        x = sample_sites(local_eval.problem(), sites_per_run**2).to_numpy()
        mu = sm.predict_values(x)
        sigma = np.sqrt(sm.predict_variances(x))
        y_max = np.max(mu)
        t = (y_max-mu)/sigma
        EI_x = (y_max-mu)*stats.norm.cdf(t) + sigma*stats.norm.pdf(t)
        feasible_points = pd.DataFrame(data=np.concatenate((x, EI_x), axis=1), columns=variables + ['EI'])
        feasible_points = feasible_points.sort_values(by='EI', ascending=False).reset_index().drop(['EI', 'index'], axis=1)
        exp_data = feasible_points.to_numpy()

        # ensure sparse
        feasible_points = np.zeros((1,len(variables)))
        while len(feasible_points) < sites_per_run and len(exp_data) > 0:
            feasible_points = np.append(feasible_points, np.array([exp_data[0]]), axis=0)
            exp_data = exp_data[1:]
            dists = np.linalg.norm(exp_data - feasible_points[-1], axis=1)
            exp_data = exp_data[dists > eps]
    
        feasible_points = feasible_points[1:]
        # evaluate model on testing data
        feasible_points = pd.DataFrame(data=feasible_points, columns=variables)
        exp_data = evaluate_sites(local_eval, feasible_points)
        
    return exp_data

In [26]:
hs100 = HS100()
problem = hs100.problem()
nind = len(problem['variables'])
sites_per_run = 20
runs = 3
experiment_6(hs100, sites_per_run, runs)

Test evaluator hs100 with 7 variables 5.263157894736842% feasible sites
Test evaluator hs100 with 7 variables 5.263157894736842% feasible sites

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/smt/surrogate_models/krg_based.py:533: UserWarning: Warning: multiple x input features have the same value (at least same row twice).
  warnings.warn(

Test evaluator hs100 with 7 variables 10.526315789473683% feasible sites

,x1,x2,x3,x4,x5,x6,x7,f,c1,c2,c3,c4,__conviol__,__State__
0,0.652998,-2.192684,4.042493,2.496685,-4.563639,0.772955,6.816159,9.399532e+04,50.642509,113.529213,227.117706,27.620529,0.000000,Feasible
1,1.942637,-2.314103,2.627380,0.403415,-1.328336,-4.629566,-7.532781,4.865679e+03,36.785228,204.580818,-42.895293,-107.455843,1.157012,Infeasible
2,4.823099,-3.137089,3.644699,-5.052205,-5.435300,6.897758,-6.007852,2.617372e+05,-288.647195,124.428206,-258.309845,-275.424741,3.787030,Infeasible
3,0.577387,-2.875646,2.558889,-4.579420,5.822077,7.268261,-1.476799,3.917870e+05,-194.366262,231.507580,-154.329311,-80.265845,1.750369,Infeasible
4,2.671721,-3.620037,3.106657,9.170212,-0.273254,2.464475,-9.476415,9.628405e+03,-740.584741,168.201395,9.192592,-206.537816,2.194141,Infeasible
5,4.181250,-0.521765,4.827721,5.454724,6.085349,-0.791513,-2.589425,5.093469e+05,-62.458593,21.858249,75.084649,-147.888430,1.480203,Infeasible
6,-3.183208,-3.108262,4.924690,2.003261,-0.131650,8.491229,-7.054204,5.338166e+03,-193.605857,68.946649,-229.486981,-189.067336,2.979691,Infeasible
7,-3.515870,-0.927213,2.384599,0.204240,-0.594717,1.040327,-6.939643,3.801487e+03,100.482073,251.730666,213.994456,-133.435535,1.334355,Infeasible
8,-5.054421,-1.760116,2.126198,6.442175,-5.368912,-3.480555,8.920204,2.472667e+05,-94.175451,265.643051,307.829738,27.885997,0.094175,Infeasible
9,-1.871213,-3.875953,5.444835,8.248023,-8.380426,1.328437,-4.972225,3.467129e+06,-792.738069,-6.364419,173.648624,-127.899691,1.506093,Infeasible
10,4.220344,-4.707006,3.981392,5.972442,-6.684035,7.617237,-5.931294,8.952800e+05,-1494.515876,95.407290,-318.807962,-288.030038,4.549017,Infeasible
11,4.967124,-0.827787,1.990073,0.647131,1.745015,9.243738,-6.215743,3.745616e+03,63.856469,211.207488,-481.335204,-234.222327,5.352977,Infeasible
12,-5.006312,-1.347865,1.104607,-0.651164,-9.149335,-8.333854,-9.162512,5.874845e+06,109.918061,300.388048,-180.690431,-143.384540,2.306689,Infeasible
13,4.269323,0.642829,3.009844,9.640684,-9.459055,7.706694,1.700285,7.163908e+06,-237.452222,140.494909,-245.364144,-103.037017,2.671779,Infeasible
14,5.925639,0.161017,5.132117,5.183893,-1.601890,2.170786,-2.856071,1.807043e+03,-47.842061,-30.134544,8.561945,-232.564275,2.345573,Infeasible
15,0.503486,-2.142260,0.478741,2.676411,1.579421,-8.276099,-0.727952,1.997558e+03,26.280081,281.513461,-236.956009,24.075575,2.369560,Infeasible
16,-4.553495,-1.185913,0.285802,2.331642,4.373568,-0.495027,9.283347,7.867108e+04,35.697724,318.657303,372.120464,36.285074,0.000000,Feasible
17,-7.341658,-0.685632,1.887785,-2.951051,-6.439095,8.433120,-5.975659,7.164094e+05,14.010022,296.323139,-110.122262,-315.994174,3.346330,Infeasible
18,-3.548602,-0.310101,-2.721316,-9.772674,7.844536,-7.788878,1.900447,2.333106e+06,-316.734909,251.332104,-71.274500,-2.127012,0.780243,Infeasible