In [24]:
from problems.HS100 import HS100, CallableClass
import methods.methods as methods
from typing import Tuple, Union, List, Type
from copy import deepcopy
import pandas as pd
import numpy as np
from numpy import number
from scipy.stats.qmc import LatinHypercube as lhs
from scipy.stats.qmc import scale
import scipy.stats as stats
from smt.surrogate_models import KRG
import random
import itertools

In [25]:
def sample_sites(problem: dict, n_samples: int, seed=random.randint(1,1000)) -> pd.DataFrame:
    """ Simple wrapper to sample sites
    
    Parameters
    ----------
    problem : dict
        The variables and constraints given

    n_sample: int
        The number of sites to generare

    seed: int
        Seed for the LHS sampling
   
    Returns
    -------
    pd.DataFrame
        The DataFrame of sites
    """

    variables = list(problem["variables"].keys())
    nind = len(variables)
    # Get all the bounds for the variables
    bounds = np.array([problem["variables"][var]["bounds"] for var in variables])
    # Generate the experiment 
    lhs_instance = lhs(
        nind,
        scramble=True,
        strength=1,
        optimization=None,
        seed=seed,
    )
    # Get the experiment
    normalized_array = lhs_instance.random(n_samples)
    # Scale using the bounds
    exp_array = scale(normalized_array, bounds[:, 0], bounds[:, 1])
    # Create the DataFrame
    exp_df = pd.DataFrame(data=exp_array, columns=variables)
    return(exp_df)

In [26]:
# CURRENTLY BROKEN
def sample_sites_uniformly(problem : dict, fineness=50) -> pd.DataFrame:
    variables = list(problem["variables"].keys())
    nind = len(variables)
    # Get all the bounds for the variables
    bounds = np.array([problem["variables"][var]["bounds"] for var in variables])
    exp_data = pd.DataFrame(data=a, columns=variables)
    return exp_data

In [27]:
def evaluate_sites(local_eval: CallableClass, exp_data: pd.DataFrame, verbose=True):
    """ evaluates sites passed and returns their constraint violation data

        Parameters
        ----------
        local_eval : CallableClass
            The example evaluator to use
        
        n_sample: int
            The number of sites to generare
   
        Returns
        -------
        pd.DataFrame
            The DataFrame of evaluated experimental sites with constraint violation
    """
    eps = 1e-6
    local_problem = local_eval.problem()
    local_eval(exp_data)
    my_constraint_calculator = methods.ConstraintCalculator(local_problem)
    exp_data['__conviol__'] = my_constraint_calculator(exp_data)
    exp_data['__State__'] = pd.cut(exp_data['__conviol__'], [-np.inf, eps, 100*eps, np.inf], include_lowest=True, labels=['Feasible', 'Nearly Feasible', "Infeasible"]).astype("str")
    feasible_sites = (exp_data['__State__'] == 'Feasible').sum()
    percentage = feasible_sites/num_sites * 100
    if verbose: 
        print(f"Test evaluator {local_eval.name} with {len(local_problem['variables'])} variables {percentage}% feasible sites")
    return (exp_data)

In [28]:
def advanced_testing(local_eval: CallableClass, num_sites_training: int, num_sites_testing : int, verbose=True) -> pd.DataFrame:
    """ Wrapper to create an experiment, evaluate the passed in function, create a surrogate model, evaluate model

        Parameters
        ----------
        local_eval : CallableClass
            The example evaluator to use
        
        n_sample_training: int
            The number of sites to train the sm on

        n_sample_testing: int
            The number of sites to test the sm
   
        Returns
        -------
        pd.DataFrame
            The DataFrame of evaluated experimental sites with constraint violation
    """
    # get training data
    sample_data = sample_sites(local_eval.problem(), num_sites_training)
    exp_data = evaluate_sites(local_eval, sample_data, verbose=False)
    variables = list(local_eval.problem()["variables"].keys())
    xt = exp_data[variables].to_numpy()
    yt = exp_data['__conviol__'].to_numpy()

    # create model
    sm = KRG(theta0=[1e-2])
    sm.set_training_values(xt, yt)
    sm.train()

    # get testing data
    eps = 1e-6
    x = sample_sites(local_eval.problem(), num_sites_testing).to_numpy()
    y = sm.predict_values(x).flatten()
    feasible_points = pd.DataFrame(data=x[y < eps], columns=variables)
    
    # evaluate model on testing data
    feasible_points = evaluate_sites(local_eval, feasible_points, verbose=verbose)
    return (feasible_points)

In [29]:
hs100 = HS100()
problem = hs100.problem()
nind = len(problem['variables'])
num_sites = 50
test_data = advanced_testing(hs100, num_sites, num_sites**2)
test_data

___________________________________________________________________________

                                  Kriging
___________________________________________________________________________

 Problem size

      # training points.        : 50

___________________________________________________________________________

 Training

   Training ...
   Training - done. Time (sec):  2.1175220
___________________________________________________________________________

 Evaluation

      # eval points. : 2500

   Predicting ...
   Predicting - done. Time (sec):  0.0518820

   Prediction time/pt. (sec) :  0.0000208

Test evaluator hs100 with 7 variables 24.0% feasible sites

,x1,x2,x3,x4,x5,x6,x7,f,c1,c2,c3,c4,__conviol__,__State__
0,1.914673,1.900237,-1.664250,1.490588,9.400737,2.168524,8.499961,6.907888e+06,26.325432,243.109455,188.136325,69.757696,0.000000,Feasible
1,2.256656,3.442284,3.244763,-6.861696,1.278743,-5.983872,7.637009,5.371687e+03,-502.373895,158.732130,-21.496674,83.954339,0.546434,Infeasible
2,-0.493005,2.148948,2.732978,-6.672214,0.600702,4.711212,7.030368,3.950963e+03,-121.273578,211.585431,125.790962,30.071124,0.121274,Infeasible
3,-0.727462,2.581102,-3.302663,4.411268,8.923691,-2.531646,3.862505,5.050827e+06,-126.361507,174.785537,198.514190,18.918771,0.126362,Infeasible
4,2.382340,-2.977504,-4.986229,8.153510,-0.902927,4.146844,5.831052,2.919141e+03,-376.562006,16.574879,75.811165,-59.165595,0.701324,Infeasible
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,0.173155,2.845153,6.871670,1.690355,3.078416,-1.871005,8.701942,1.728884e+04,-103.334830,-198.557936,232.534112,3.899829,1.988266,Infeasible
58,-2.493330,-1.710779,-1.155280,4.655199,3.690457,-6.452397,7.431111,3.001904e+04,-15.111800,290.274187,60.068155,96.337933,0.015112,Infeasible
59,4.321534,0.559627,-0.894331,8.388607,-8.483611,2.435597,9.111193,3.735529e+06,-148.808056,225.199889,133.588306,18.685028,0.148808,Infeasible
60,0.232339,1.372312,1.937037,1.570315,7.110905,-7.530112,0.964377,1.294289e+06,68.897153,244.276154,-143.727507,39.611838,1.437275,Infeasible
61,0.244562,1.478966,0.536098,-5.396578,-6.467513,-1.256336,9.173280,7.403857e+05,27.836228,271.906224,252.103706,105.271473,0.000000,Feasible

## Experiment 3
1. Generate training data once and train
2. Regenerate sites, pass through filter, take the top sites
3. Train again, and repeat

In [45]:
# multi-run training
def experiment_3(local_eval, sites_per_run, runs, verbose=False):
    problem = hs100.problem()
    nind = len(problem['variables'])

    # create model
    sm = KRG(theta0=[1e-2], print_global=False)
    
    for i in range(runs):
        if i == 0:
            # get first run's data
            sample_data = sample_sites(local_eval.problem(), sites_per_run)
            exp_data = evaluate_sites(local_eval, sample_data, verbose=False)
        variables = list(local_eval.problem()["variables"].keys())
        xt = exp_data[variables].to_numpy()
        yt = exp_data['__conviol__'].to_numpy()
        
        # train model
        sm.set_training_values(xt, yt)
        sm.train()
    
        # get next run's data
        x = sample_sites(local_eval.problem(), sites_per_run**2).to_numpy()
        y = sm.predict_values(x)
        exp_data = pd.DataFrame(data=np.concatenate((x,y), axis=1), columns=variables + ['conviol'])
        exp_data = exp_data.sort_values(by='conviol').reset_index()[:sites_per_run].drop('conviol',axis=1)
        # evaluate model on testing data
        exp_data = evaluate_sites(local_eval, exp_data)
    return exp_data

In [56]:
hs100 = HS100()
problem = hs100.problem()
nind = len(problem['variables'])
num_sites = 40
runs = 3
experiment_3(hs100, num_sites, runs)

Test evaluator hs100 with 7 variables 22.5% feasible sites
Test evaluator hs100 with 7 variables 0.0% feasible sites
Test evaluator hs100 with 7 variables 12.5% feasible sites

,index,x1,x2,x3,x4,x5,x6,x7,f,c1,c2,c3,c4,__conviol__,__State__
0,731,-1.353791,0.970578,1.192951,7.193741,10.055978,-3.416546,6.739233,1.034360e+07,-137.800203,277.195719,210.072285,76.153129,0.137800,Infeasible
1,325,-0.228923,2.011239,4.011603,-2.898080,-1.408625,-4.665249,8.336312,6.637391e+03,47.243147,118.128591,133.323361,77.203797,0.000000,Feasible
2,1556,-2.826874,0.407453,1.213080,2.796731,-3.034623,-1.801798,6.912904,1.116908e+04,93.608085,280.018767,296.676466,46.521457,0.000000,Feasible
3,667,0.378676,0.871812,6.232803,8.867051,7.063383,-5.029453,7.366368,1.247367e+06,-231.067954,-113.548144,93.688975,28.138418,1.158754,Infeasible
4,538,-3.009911,2.543201,4.853304,1.821134,-5.561150,-0.782243,8.540354,3.025071e+05,-6.932895,52.511848,323.411498,-14.924579,0.149407,Infeasible
5,1227,-1.482483,2.352430,8.269647,-8.363031,3.504628,0.640362,3.889889,2.511211e+04,-274.822489,-386.682824,253.221923,-121.974416,4.063947,Infeasible
6,771,-0.071145,-0.485545,4.747013,-4.909888,7.270602,1.903341,3.364850,1.479372e+06,-10.704893,70.793863,202.583129,-17.723983,0.177563,Infeasible
7,1487,0.650304,0.421801,8.616535,4.689489,-6.251351,-3.541241,1.390092,6.033447e+05,60.734253,-477.205070,116.743521,-116.538721,4.912290,Infeasible
8,1182,-0.880484,3.307464,-7.167954,8.304643,-0.020448,-1.833845,6.679886,5.186303e+03,-502.154755,-243.879725,238.572971,-42.887979,2.526624,Infeasible
9,1417,1.358584,1.908318,6.461095,-2.669394,-8.717096,-3.960596,-0.383194,4.390673e+06,92.144780,-156.740218,63.927412,-71.150494,1.721333,Infeasible
10,389,1.095763,2.096936,2.530613,3.377062,1.868902,-5.828859,6.042666,2.933008e+03,9.100713,202.490673,10.888082,80.498929,0.000000,Feasible
11,453,-3.533351,1.522428,9.277278,-8.771965,6.597595,1.283962,0.125419,8.340437e+05,-264.140290,-543.143076,266.061288,-245.569847,5.966629,Infeasible
12,1384,2.112611,0.155200,9.364172,9.263889,4.184810,0.440622,-0.310626,6.217183e+04,-255.494757,-615.210189,143.735975,-197.888388,6.467582,Infeasible
13,899,1.447832,2.132981,-0.713333,-3.904480,-1.184085,-0.507799,-1.283464,1.271438e+03,6.364701,263.098187,146.335384,-16.266679,0.162667,Infeasible
14,581,1.560430,-0.830232,-0.077932,-3.937602,4.999186,2.943046,7.459544,1.606412e+05,33.767931,282.443740,167.128066,53.011993,0.000000,Feasible
15,756,0.310479,-0.392583,9.793332,-0.817834,6.221840,5.512707,8.018833,5.946444e+05,83.158000,-671.049446,70.515883,-132.080458,6.839244,Infeasible
16,277,-1.251626,1.619372,-0.460873,-0.543569,2.145636,-0.943051,-3.948288,2.316304e+03,91.787260,286.468430,185.242651,-54.109906,0.541099,Infeasible
17,1470,-0.309038,0.618371,9.483136,-6.531174,9.358274,2.417742,-3.644614,6.727008e+06,-100.529078,-601.100992,138.495705,-233.376884,6.448940,Infeasible
18,550,-3.857942,2.763434,7.008180,7.531682,-9.424298,-1.701605,0.466823,7.009489e+06,-264.510624,-207.386555,263.457933,-183.741042,2.783336,Infeasible
19,1370,2.765030,1.769284,1.397587,8.212488,-4.981031,0.302508,0.743319,1.533208e+05,-163.960635,224.610934,134.671415,-16.278096,0.231043,Infeasible
20,954,-2.721922,2.037096,-2.822466,8.253272,8.863824,-3.064018,-2.126228,4.850686e+06,-253.441904,215.889571,181.115390,-74.420704,0.786179,Infeasible
21,818,2.897090,2.657407,-2.393057,-2.197599,-9.077187,-4.581734,3.429757,5.595219e+06,-10.932643,189.601349,23.789438,31.644465,0.010933,Infeasible
22,657,-2.693315,1.799545,-7.935853,1.501460,2.232569,0.112403,1.650576,6.148982e+03,68.786648,-333.591971,267.836674,-155.155568,3.679088,Infeasible
23,1573,-3.773500,-0.057306,6.320923,4.474792,6.807628,-5.981661,6.656393,1.000368e+06,-21.932751,-88.621479,121.356778,-33.091270,0.946235,Infeasible
24,1100,0.299705,0.860377,-1.221415,-5.464066,8.008530,1.508335,-0.851108,2.639799e+06,-33.068845,275.874992,167.907246,-20.213529,0.204822,Infeasible
25,841,1.008337,-2.474658,-0.774514,-4.356985,9.591373,-0.588172,9.038710,7.793937e+06,-110.656676,290.315252,236.918330,83.490160,0.110657,Infeasible
26,951,-2.898260,2.790527,-9.558786,-9.406667,-1.744789,-3.116542,3.165029,1.068406e+04,-407.372651,-612.125783,221.916165,-197.992441,6.446383,Infeasible
27,24,-3.593206,1.724900,10.011478,-8.630112,1.077397,0.061297,-6.681893,1.397824e+04,-238.692884,-690.611691,222.190783,-347.480258,7.734706,Infeasible
28,212,0.899199,2.880919,-2.332210,9.343624,7.212884,-3.231125,-3.371334,1.408920e+06,-464.217234,210.540079,77.407064,-35.569824,0.584824,Infeasible
29,440,-1.559982,2.853366,8.483669,0.635841,-0.861115,-0.330449,-6.259827,7.639695e+03,-82.524187,-436.863602,173.004088,-242.380607,4.996662,Infeasible
30,901,1.263529,3.996442,-7.836829,5.315381,-8.145861,-0.601750,1.952822,2.925885e+06,-705.911429,-366.454110,164.417231,-105.550688,3.878307,Infeasible
31,127,-0.293335,2.909678,3.117697,1.481118,0.214857,2.039767,-1.085810,9.130924e+02,-101.169903,176.857711,160.630121,-52.953748,0.539115,Infeasible
32,1546,-1.858329,3.001047,1.957908,-7.886966,-8.243020,-7.267169,8.720717,3.145066e+06,-332.806075,247.315075,-17.369476,85.046298,0.375406,Infeasible
33,1271,-2.151019,2.915833,9.499776,1.431432,-1.569916,-6.847053,2.330743,9.600282e+03,-108.956136,-617.149166,-25.675492,-166.443715,6.398082,Infeasible
34,1161,0.485478,-1.619642,0.606553,3.518649,-3.465905,3.560337,5.296181,1.924222e+04,73.083880,272.796958,148.524222,33.795594,0.000000,Feasible
35,122,1.379893,2.292618,-6.924211,-6.852791,1.153517,-2.541592,-4.227060,4.204634e+03,-146.374165,-205.977731,86.431742,-133.060907,2.456548,Infeasible
36,1053,1.212220,2.363251,-8.838659,3.112847,0.927363,3.023398,7.434010,9.776113e+03,-4.071507,-516.979659,167.160437,-92.455186,5.251820,Infeasible
37,1419,-0.901488,-2.560506,4.979173,-5.079629,4.344242,-0.627164,2.956024,6.985614e+04,-133.487212,57.494187,231.466226,-16.814359,0.214688,Infeasible
38,1523,-1.852662,-0.987085,-4.845470,1.094108,6.008930,-1.790462,0.728281,4.726116e+05,87.299812,68.058944,224.228611,-39.211311,0.392113,Infeasible
39,123,-0.861735,-1.542615,3.575770,-4.974082,0.018662,-0.663254,-0.628231,1.977215e+03,5.891418,169.791433,205.774954,-30.528565,0.305286,Infeasible

## Experiment 4
1. Train to maximize $-\log(C+\epsilon)$
2. Filter is now if EI(x) is sufficiently large,
    $EI(x) = (f^*-\mu_f(x))\Phi\left(\frac{f^*-\mu_f(x)}{\sigma_f(x)}\right)+\sigma_f(x)\phi\left(\frac{f^*-\mu_f(x)}{\sigma_f(x)}\right)$
   where $\mu_f,\sigma_f, f^*$ are the predicted value, variance, and maximum of the sm, and $\Phi,\phi$ are normal CDF and PDF.
   
   Note: Need to choose test sites wisely and tune filter better

In [12]:
# weigh with variance
def experiment_4(local_eval, num_sites_training, num_sites_testing,verbose=True):
    # get training data
    sample_data = sample_sites(local_eval.problem(), num_sites_training)
    exp_data = evaluate_sites(local_eval, sample_data, verbose=False)
    variables = list(local_eval.problem()["variables"].keys())
    xt = exp_data[variables].to_numpy()
    yt = (-1)*np.log(exp_data['__conviol__'].to_numpy() + 1e-6)
    
    # create model
    sm = KRG(theta0=[1e-2], print_global=False)
    sm.set_training_values(xt, yt)
    sm.train()

    # compute EI(x)
    x = sample_sites(local_eval.problem(), num_sites_testing).to_numpy()
    mu = sm.predict_values(x).flatten()
    sigma = np.sqrt(sm.predict_variances(x).flatten())
    y_max = np.max(mu)
    t = (y_max-mu)/sigma
    EI_x = (y_max-mu)*stats.norm.cdf(t) + sigma*stats.norm.pdf(t)
    feasible_points = pd.DataFrame(data=x[EI_x > 5], columns=variables)
    
    # evaluate model on testing data
    feasible_points = evaluate_sites(local_eval, feasible_points, verbose=verbose)
    return (feasible_points)

In [13]:
hs100 = HS100()
problem = hs100.problem()
nind = len(problem['variables'])
num_sites = 25
experiment_4(hs100, num_sites, num_sites**2)

Test evaluator hs100 with 7 variables 8.0% feasible sites

,x1,x2,x3,x4,x5,x6,x7,f,c1,c2,c3,c4,__conviol__,__State__
0,-5.529141,-5.758379,-8.743796,-2.246104,3.816640,5.953620,2.898170,3.926565e+04,-3263.206691,-420.497861,100.523115,-210.724030,5.724581,Infeasible
1,9.818763,-3.194266,4.946372,-9.689501,-1.825226,-2.381453,-0.948382,3.469760e+03,-749.506437,-13.950216,-81.649846,-537.385115,5.488731,Infeasible
2,-5.104010,9.435533,-3.590033,2.458193,4.977514,9.688073,1.711252,1.532157e+05,-23749.207818,163.057430,-325.099596,-393.103360,24.290880,Infeasible
3,4.778466,-5.511930,6.538125,0.574757,-3.733520,8.169195,-4.962849,3.199183e+04,-2676.942623,-166.692543,-384.403321,-381.663500,6.268011,Infeasible
4,-7.079450,5.410729,0.845053,-5.885154,-8.109177,7.503834,-0.415930,2.845249e+06,-2643.326158,305.958802,-11.621191,-388.188020,4.697837,Infeasible
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
605,8.523849,5.921021,5.540704,-2.711425,8.459330,-6.378782,4.994850,3.667261e+06,-3782.848782,-91.253210,-239.281401,-148.834381,4.804517,Infeasible
606,5.711529,4.348007,-4.848890,-4.507684,2.145181,-7.233120,-5.766094,3.983204e+03,-1097.612667,0.510823,-314.307210,-149.175007,3.648147,Infeasible
607,-9.345215,-7.620601,-1.615610,9.508069,7.776385,5.154177,4.755073,2.214218e+06,-10564.159378,342.444659,231.513743,-172.442722,10.703976,Infeasible
608,-4.996386,6.993529,0.753814,4.765775,-2.972873,-9.486564,-2.773710,8.071411e+03,-7176.068861,282.573102,-300.151593,-237.806477,8.133895,Infeasible
609,4.424525,2.776372,6.838417,-1.181164,-1.102575,-2.335586,-0.661125,3.167282e+03,-97.309822,-224.861734,48.508925,-138.283905,2.641589,Infeasible